// Generated by gencpp from file roborts_msgs/chassis_info.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_CHASSIS_INFO_H
#define ROBORTS_MSGS_MESSAGE_CHASSIS_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct chassis_info_
{
  typedef chassis_info_<ContainerAllocator> Type;

  chassis_info_()
    : chassis_mode(0)
    , chassis_x(0.0)
    , chassis_y(0.0)
    , chassis_r(0.0)  {
    }
  chassis_info_(const ContainerAllocator& _alloc)
    : chassis_mode(0)
    , chassis_x(0.0)
    , chassis_y(0.0)
    , chassis_r(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _chassis_mode_type;
  _chassis_mode_type chassis_mode;

   typedef float _chassis_x_type;
  _chassis_x_type chassis_x;

   typedef float _chassis_y_type;
  _chassis_y_type chassis_y;

   typedef float _chassis_r_type;
  _chassis_r_type chassis_r;





  typedef boost::shared_ptr< ::roborts_msgs::chassis_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::chassis_info_<ContainerAllocator> const> ConstPtr;

}; // struct chassis_info_

typedef ::roborts_msgs::chassis_info_<std::allocator<void> > chassis_info;

typedef boost::shared_ptr< ::roborts_msgs::chassis_info > chassis_infoPtr;
typedef boost::shared_ptr< ::roborts_msgs::chassis_info const> chassis_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::chassis_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::chassis_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/chassis', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/feedback', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/gimbal', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::chassis_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::chassis_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::chassis_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::chassis_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::chassis_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::chassis_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::chassis_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f7db8c7808f9a47fe9116576ce31396";
  }

  static const char* value(const ::roborts_msgs::chassis_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f7db8c7808f9a47ULL;
  static const uint64_t static_value2 = 0xfe9116576ce31396ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::chassis_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/chassis_info";
  }

  static const char* value(const ::roborts_msgs::chassis_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::chassis_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   chassis_mode\n\
float32 chassis_x\n\
float32 chassis_y\n\
float32 chassis_r\n\
";
  }

  static const char* value(const ::roborts_msgs::chassis_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::chassis_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_mode);
      stream.next(m.chassis_x);
      stream.next(m.chassis_y);
      stream.next(m.chassis_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassis_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::chassis_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::chassis_info_<ContainerAllocator>& v)
  {
    s << indent << "chassis_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chassis_mode);
    s << indent << "chassis_x: ";
    Printer<float>::stream(s, indent + "  ", v.chassis_x);
    s << indent << "chassis_y: ";
    Printer<float>::stream(s, indent + "  ", v.chassis_y);
    s << indent << "chassis_r: ";
    Printer<float>::stream(s, indent + "  ", v.chassis_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_CHASSIS_INFO_H
