// Generated by gencpp from file roborts_msgs/chassis_ctrl.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_CHASSIS_CTRL_H
#define ROBORTS_MSGS_MESSAGE_CHASSIS_CTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct chassis_ctrl_
{
  typedef chassis_ctrl_<ContainerAllocator> Type;

  chassis_ctrl_()
    : cmd_chassis_mode(0)
    , cmd_chassis_x(0.0)
    , cmd_chassis_y(0.0)
    , cmd_chassis_r(0.0)  {
    }
  chassis_ctrl_(const ContainerAllocator& _alloc)
    : cmd_chassis_mode(0)
    , cmd_chassis_x(0.0)
    , cmd_chassis_y(0.0)
    , cmd_chassis_r(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _cmd_chassis_mode_type;
  _cmd_chassis_mode_type cmd_chassis_mode;

   typedef float _cmd_chassis_x_type;
  _cmd_chassis_x_type cmd_chassis_x;

   typedef float _cmd_chassis_y_type;
  _cmd_chassis_y_type cmd_chassis_y;

   typedef float _cmd_chassis_r_type;
  _cmd_chassis_r_type cmd_chassis_r;





  typedef boost::shared_ptr< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct chassis_ctrl_

typedef ::roborts_msgs::chassis_ctrl_<std::allocator<void> > chassis_ctrl;

typedef boost::shared_ptr< ::roborts_msgs::chassis_ctrl > chassis_ctrlPtr;
typedef boost::shared_ptr< ::roborts_msgs::chassis_ctrl const> chassis_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::chassis_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/chassis', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/feedback', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/gimbal', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d718a58c641ad306069461333848a771";
  }

  static const char* value(const ::roborts_msgs::chassis_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd718a58c641ad306ULL;
  static const uint64_t static_value2 = 0x069461333848a771ULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/chassis_ctrl";
  }

  static const char* value(const ::roborts_msgs::chassis_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   cmd_chassis_mode\n\
float32 cmd_chassis_x\n\
float32 cmd_chassis_y\n\
float32 cmd_chassis_r\n\
";
  }

  static const char* value(const ::roborts_msgs::chassis_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_chassis_mode);
      stream.next(m.cmd_chassis_x);
      stream.next(m.cmd_chassis_y);
      stream.next(m.cmd_chassis_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassis_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::chassis_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::chassis_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "cmd_chassis_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_chassis_mode);
    s << indent << "cmd_chassis_x: ";
    Printer<float>::stream(s, indent + "  ", v.cmd_chassis_x);
    s << indent << "cmd_chassis_y: ";
    Printer<float>::stream(s, indent + "  ", v.cmd_chassis_y);
    s << indent << "cmd_chassis_r: ";
    Printer<float>::stream(s, indent + "  ", v.cmd_chassis_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_CHASSIS_CTRL_H
