// Generated by gencpp from file roborts_msgs/gimbal_info.msg
// DO NOT EDIT!


#ifndef ROBORTS_MSGS_MESSAGE_GIMBAL_INFO_H
#define ROBORTS_MSGS_MESSAGE_GIMBAL_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roborts_msgs
{
template <class ContainerAllocator>
struct gimbal_info_
{
  typedef gimbal_info_<ContainerAllocator> Type;

  gimbal_info_()
    : gimbal_mode(0)
    , gimbal_yaw(0.0)
    , gimbal_pitch(0.0)  {
    }
  gimbal_info_(const ContainerAllocator& _alloc)
    : gimbal_mode(0)
    , gimbal_yaw(0.0)
    , gimbal_pitch(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _gimbal_mode_type;
  _gimbal_mode_type gimbal_mode;

   typedef float _gimbal_yaw_type;
  _gimbal_yaw_type gimbal_yaw;

   typedef float _gimbal_pitch_type;
  _gimbal_pitch_type gimbal_pitch;





  typedef boost::shared_ptr< ::roborts_msgs::gimbal_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roborts_msgs::gimbal_info_<ContainerAllocator> const> ConstPtr;

}; // struct gimbal_info_

typedef ::roborts_msgs::gimbal_info_<std::allocator<void> > gimbal_info;

typedef boost::shared_ptr< ::roborts_msgs::gimbal_info > gimbal_infoPtr;
typedef boost::shared_ptr< ::roborts_msgs::gimbal_info const> gimbal_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roborts_msgs::gimbal_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roborts_msgs::gimbal_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roborts_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'roborts_msgs': ['/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/chassis', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/feedback', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/gimbal', '/home/dji/hyy_ws/src/8.6 No.4/roborts_msgs/referee_system'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roborts_msgs::gimbal_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roborts_msgs::gimbal_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roborts_msgs::gimbal_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff1dad119a0d9688115465f7f16fbe0b";
  }

  static const char* value(const ::roborts_msgs::gimbal_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff1dad119a0d9688ULL;
  static const uint64_t static_value2 = 0x115465f7f16fbe0bULL;
};

template<class ContainerAllocator>
struct DataType< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roborts_msgs/gimbal_info";
  }

  static const char* value(const ::roborts_msgs::gimbal_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   gimbal_mode\n\
float32 gimbal_yaw\n\
float32 gimbal_pitch\n\
";
  }

  static const char* value(const ::roborts_msgs::gimbal_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gimbal_mode);
      stream.next(m.gimbal_yaw);
      stream.next(m.gimbal_pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gimbal_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roborts_msgs::gimbal_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roborts_msgs::gimbal_info_<ContainerAllocator>& v)
  {
    s << indent << "gimbal_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gimbal_mode);
    s << indent << "gimbal_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.gimbal_yaw);
    s << indent << "gimbal_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.gimbal_pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBORTS_MSGS_MESSAGE_GIMBAL_INFO_H
