# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/chassis_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class chassis_info(genpy.Message):
  _md5sum = "1f7db8c7808f9a47fe9116576ce31396"
  _type = "roborts_msgs/chassis_info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8   chassis_mode
float32 chassis_x
float32 chassis_y
float32 chassis_r"""
  __slots__ = ['chassis_mode','chassis_x','chassis_y','chassis_r']
  _slot_types = ['uint8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       chassis_mode,chassis_x,chassis_y,chassis_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(chassis_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.chassis_mode is None:
        self.chassis_mode = 0
      if self.chassis_x is None:
        self.chassis_x = 0.
      if self.chassis_y is None:
        self.chassis_y = 0.
      if self.chassis_r is None:
        self.chassis_r = 0.
    else:
      self.chassis_mode = 0
      self.chassis_x = 0.
      self.chassis_y = 0.
      self.chassis_r = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.chassis_mode, _x.chassis_x, _x.chassis_y, _x.chassis_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.chassis_mode, _x.chassis_x, _x.chassis_y, _x.chassis_r,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.chassis_mode, _x.chassis_x, _x.chassis_y, _x.chassis_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.chassis_mode, _x.chassis_x, _x.chassis_y, _x.chassis_r,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3f = None
def _get_struct_B3f():
    global _struct_B3f
    if _struct_B3f is None:
        _struct_B3f = struct.Struct("<B3f")
    return _struct_B3f
