# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roborts_msgs/gimbal_ctrl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class gimbal_ctrl(genpy.Message):
  _md5sum = "31acb477b7f21d2e6fa8ecbdc101a6b4"
  _type = "roborts_msgs/gimbal_ctrl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8   cmd_gimbal_mode
float32 cmd_gimbal_yaw
float32 cmd_gimbal_pitch
uint8   cmd_gimbal_fric_speed"""
  __slots__ = ['cmd_gimbal_mode','cmd_gimbal_yaw','cmd_gimbal_pitch','cmd_gimbal_fric_speed']
  _slot_types = ['uint8','float32','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cmd_gimbal_mode,cmd_gimbal_yaw,cmd_gimbal_pitch,cmd_gimbal_fric_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gimbal_ctrl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.cmd_gimbal_mode is None:
        self.cmd_gimbal_mode = 0
      if self.cmd_gimbal_yaw is None:
        self.cmd_gimbal_yaw = 0.
      if self.cmd_gimbal_pitch is None:
        self.cmd_gimbal_pitch = 0.
      if self.cmd_gimbal_fric_speed is None:
        self.cmd_gimbal_fric_speed = 0
    else:
      self.cmd_gimbal_mode = 0
      self.cmd_gimbal_yaw = 0.
      self.cmd_gimbal_pitch = 0.
      self.cmd_gimbal_fric_speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2fB().pack(_x.cmd_gimbal_mode, _x.cmd_gimbal_yaw, _x.cmd_gimbal_pitch, _x.cmd_gimbal_fric_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.cmd_gimbal_mode, _x.cmd_gimbal_yaw, _x.cmd_gimbal_pitch, _x.cmd_gimbal_fric_speed,) = _get_struct_B2fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2fB().pack(_x.cmd_gimbal_mode, _x.cmd_gimbal_yaw, _x.cmd_gimbal_pitch, _x.cmd_gimbal_fric_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.cmd_gimbal_mode, _x.cmd_gimbal_yaw, _x.cmd_gimbal_pitch, _x.cmd_gimbal_fric_speed,) = _get_struct_B2fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2fB = None
def _get_struct_B2fB():
    global _struct_B2fB
    if _struct_B2fB is None:
        _struct_B2fB = struct.Struct("<B2fB")
    return _struct_B2fB
